// Cetățenii posibile — „Română” prima opțiune (cea mai frecventă), restul alfabetic.
export const CETATENII: string[] = [
  'Română',
  'Afgană', 'Albaneză', 'Algeriană', 'Americană', 'Andorrană', 'Angoleză',
  'Antiguană', 'Argentiniană', 'Armeană', 'Australiană', 'Austriacă', 'Azeră',
  'Bahameză', 'Bahreiniană', 'Bangladeză', 'Barbadiană', 'Belaruse', 'Belgiană',
  'Belizeană', 'Beniniană', 'Bhutaneză', 'Bolgariană', 'Boliviană', 'Bosniacă',
  'Botswaneză', 'Braziliană', 'Britanică', 'Bruneiană', 'Bulgară', 'Burkinabeză',
  'Burundeză', 'Cambodgiană', 'Cameruneză', 'Canadiană', 'Capverdiană',
  'Cehă', 'Chiliană', 'Chineză', 'Cipriotă', 'Columbiană', 'Congoleză',
  'Costaricană', 'Croată', 'Cubaneză', 'Daneză', 'Djiboutiană', 'Dominicană',
  'Ecuadoriană', 'Ecuatoguineeană', 'Egipteană', 'Emirateză', 'Eritreeană',
  'Estoniană', 'Etiopiană', 'Fijiană', 'Filipineză', 'Finlandeză', 'Franceză',
  'Gaboneză', 'Gambiană', 'Georgiană', 'Ghaneză', 'Greacă', 'Grenadiană',
  'Guatemaleză', 'Guineeană', 'Guyaneză', 'Haitiană', 'Honduriană', 'Indiană',
  'Indoneziană', 'Iordaniană', 'Irakiană', 'Iraniană', 'Irlandeză', 'Islandeză',
  'Israeliană', 'Italiană', 'Ivoriană', 'Jamaicană', 'Japoneză', 'Kazahă',
  'Keniană', 'Kârgâză', 'Kosovară', 'Kuweitiană', 'Laoțiană', 'Lesothoană',
  'Letonă', 'Liberiană', 'Libaneză', 'Libiană', 'Liechtensteineză', 'Lituaniană',
  'Luxemburgheză', 'Macedoneană', 'Madagascariană', 'Malaeziană', 'Malawiană',
  'Maldiveză', 'Maliană', 'Malteză', 'Marocană', 'Mauritaneză', 'Mauriciană',
  'Mexicană', 'Moldovenească', 'Monegască', 'Mongolă', 'Muntenegreană',
  'Mozambicană', 'Myanmareză', 'Namibiană', 'Nepaleză', 'Nicaraguană',
  'Nigeriană', 'Nord-coreeană', 'Norvegiană', 'Olandeză', 'Omaneză',
  'Pakistaneză', 'Palestiniană', 'Panameză', 'Papuană', 'Paraguayană',
  'Peruană', 'Poloneză', 'Portugheză', 'Qatariană', 'Rusă', 'Rwandeză',
  'Salvadoriană', 'Samoană', 'Sanmarineză', 'Saudită', 'Senegaleză',
  'Sârbă', 'Seychelleză', 'Sierraleoneză', 'Singaporeză', 'Siriană',
  'Slovacă', 'Slovenă', 'Solomoneză', 'Somaleză', 'Spaniolă', 'Sri lankeză',
  'Sudaneză', 'Sud-africană', 'Sud-coreeană', 'Sud-sudaneză', 'Suedeză',
  'Surinameză', 'Tadjică', 'Tanzaniană', 'Thailandeză', 'Timoreză', 'Togoleză',
  'Tongană', 'Trinidadiană', 'Tunisiană', 'Turcă', 'Turkmenă', 'Ucraineană',
  'Ugandeză', 'Ungară', 'Uruguayană', 'Uzbecă', 'Vanuatuană', 'Venezueleană',
  'Vietnameză', 'Yemenită', 'Zambiană', 'Zimbabweană',
]
